version: "3.8"

services:
  mock_code_api:
    image: mock_code_api:dev
    build:
      context: backend
      dockerfile: dockerfile
    container_name: mock_code_api
    ports:
      - "6005:5000"
    env_file:
      - backend/.env
    depends_on:
      - mock_code_db
    volumes:
      - ./backend:/code
    command: ["air", "-c", ".air.toml"]

  mock_code_db:
    image: postgres:15.3
    container_name: mock_code_db
    volumes:
      - mock_code_db_data:/var/lib/postgresql/data/
    ports:
      - "5544:5432"
    env_file:
      - backend/.env

  mock_code_web:
    image: mock_code_web:dev
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - APP_BASE_URL=http://localhost:6005/api
    container_name: mock_code_web
    ports:
      - "6006:3000"
    environment:
      - APP_BASE_URL=http://mock_code_api:5000/api
    depends_on:
      - mock_code_api
    volumes:
      - ./frontend:/code
    # command: ["next", "dev"]

volumes:
  mock_code_db_data:
